################################################################################################
# Requirements & Config.
################################################################################################


#-----------------------------------------------
# Build Settings
#-----------------------------------------------
markdown: kramdown
permalink: pretty
sass:
  style: compressed
  sass_dir: _sass

#-----------------------------------------------
# Plugins
#-----------------------------------------------
plugins:
  - jekyll-sitemap
  - jekyll-autoprefixer

exclude: ['README.md', 'LICENSE.txt', 'CNAME', 'vendor', 'Gemfile', 'Gemfile.lock']

################################################################################################
# Site Settings
################################################################################################
title: "BSidesNYC"
email: "bsides@bsidesnyc.org"
twitterAccount: "@bsidesnyc"
description: "BSides NYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community, and we truly strive to keep information free."
url: "https://bsidesnyc.org" #https://bsidesnyc.github.io
timezone: "America/New_York"
conYear: "2026"
previousSponsorCount: "22"
previousAttendeeCount: "1000"
logoImage: "/about/logo_white.webp"
contactUs: "/about/#contact-us"

# 
# Slack Invite URL
# Also change this in the links section below
#
slackInviteUrl: https://join.slack.com/t/bsidesnyc/shared_invite/zt-3ehtljcnl-bzDSX_sPOAVwiEPFDg18rA

#-----------------------------------------------
# Footer
#-----------------------------------------------
socialLinks:
  - icon: twitter
    link: https://twitter.com/bsidesnyc
  - icon: linkedin
    link: https://www.linkedin.com/company/bsidesnyc
  - icon: mastodon
    link: https://infosec.exchange/@BSidesNYC

footerBlocks:
  - title: Links
    links:
      - text: BSidesNYC
        permalink: /
      - text: Security BSides
        link: http://www.securitybsides.com
  - title: Contacts
    links:
      - text: Mailing List
        permalink: /about/#contact-us
      - text: Join our Slack
        link: https://join.slack.com/t/bsidesnyc/shared_invite/zt-3ehtljcnl-bzDSX_sPOAVwiEPFDg18rA
      - text: "bsides(at)bsidesnyc.org"
        link: mailto:bsides@bsidesnyc.org
      - text: Volunteer
        permalink: /about/#volunteers
  - title: Policies
    links:
      - text: "CoC & Anti-Harassment"
        permalink: /policies/
  - title: Press
    links:
      - text: Press Passes
        permalink: /about/#contact-us
      - text: Logo Kit 
        permalink: /assets/bsidesnyc_logo_original.zip

#-----------------------------------------------
# Head
#-----------------------------------------------
metaKeywords: "bsides, security, bsidesnyc, conference, nyc"
socialImageSrcTwitter: "/img/seo/sharing-twitter.webp"
socialImageSrcFacebook: "/img/seo/sharing-facebook.webp"

#-----------------------------------------------
# Navigation
#-----------------------------------------------
navigationLinks:
 - {permalink: "/venue/", text: "Venue"}
# - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/villages/", text: "Villages"}
# - {permalink: "/ctf/", text: "CTF"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/archive/", text: "Archive"}
# - {permalink: "/registration/", text: "Registration"}
 - {permalink: "/sponsors/", text: "Sponsors"}
 - {permalink: "/cfp/", text: "CFP"}
 - {permalink: "/about/", text: "About"}
bottomNavigationLinks:
rightNavigationButtons:

# Ordered sponsor tier list for the archive page (highest to lowest)
sponsorTiers:
 - Gigabit
 - Platinum
 - Megabit
 - Gold
 - Kilobit
 - Silver

################################################################################################
# Block Data
################################################################################################

#-----------------------------------------------
# About
#-----------------------------------------------
aboutTitle: "About BSidesNYC"
aboutCaption: "BSidesNYC is an Information / Security conference that’s different. We’re a 100% volunteer organized event put on by and for the community and we truly strive to keep information free."
aboutBlock:
  - {title: "Conference", image: "conference.webp", text: "Three technical tracks based on the themes of Red Teams, Blue Teams, and Other content. Plus an Entreprenuer track for the bold!" }
  - {title: "Villages", image: "villages.webp", text: "Discover different realms of security, hacking, and local community-driven organizations." }
  - {title: "Capture The Flag", image: "ctf.webp", text: "Multiple CTFs with varying levels of technical depth." }

# Statistic Block
statisticBlockImage: "statistic.webp"
statisticBlock:
 - {count: "1000", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "45", specialCharacter: "+", info: "hours", detail: "of security content"}
 - {count: "58", specialCharacter: "+", info: "speakers", detail: "from across the world"}
 - {count: "5", specialCharacter: "", info: "parallel tracks", detail: "plus villages"}

#-----------------------------------------------
# CFP Block
#-----------------------------------------------

cfpTitle: "Call For Papers"
cfpBoardTitle: "CFP Board"
cfpUrl: # "https://docs.google.com/forms/d/e/1FAIpQLSes8dIfojKqXatyC6lNug41d_jsnio0LdIZRlFWms9sbWiUxw/viewform?usp=sf_link"
cfpShowTechMembers: false
cfpShowEntrepreneurMembers: false
cfpOpenDate: "April 16, 2026"
cfpCloseDate: "July 19, 2026"
cfpAcceptanceDate: "July 19, 2026"
cfpDuration: "CFP submissions will be accepted from"
cfpAcceptance: "Speaker acceptance notices will start being sent out on"
cfpProcessReviewText: ["Our current conference timeline allocates ~3 months for our CFP to be open for submissions.",

"After our CFP has been closed on July 19, 2026, our CFP review board has ~1 week to look over and score all submissions.",

"Based on the ratings from our CFP review board, the submissions with the highest score are put into our first round of acceptance notices, which start on July 27, 2026.",

"We allow ~1 week for these submitters to respond. <i>If we can not get a hold of, or hear back from, said submitter(s) then we move down our acceptance list</i>. Additionally, circumstatnces may arrise which prevent a submitter from being able or willing to present at our conference. If this occurs, we must once again continue down the acceptance list.",

"This is usually resolved within a week or two, but as you can imagine, we can not send out rejection notices until we have enough talks to fill our schedule.", "Once we have enough acceptances, we will send out notices to those who did not make the final cut, probably starting August 4, 2026. Depending on the volume of CFP submissions, we may not be able to provide personal feedback for each CFP submission."]
cfpProcessAcceptedText: ["Acceptance notice go out over a month ahead of the conference so you can schedule any necessary travel arrangements. <b>If your attendance requires any visa paperwork, please let us know ahead of time</b>.",

"Additionally, we will be posting the speaker list and talk abstracts so please let us know if anything has changed (title, abstract etc.) A.S.A.P.",

"As always, if you would like to have someone come to the conference with you, please just send us their information so we can register them."]

#-----------------------------------------------
# Villages
# also see _data/villages.yml
#-----------------------------------------------
villagesAboutTitle: "About Villages"
villagesTitle: "BSidesNYC 2026 Villages"
villagesUrl: "/villages/"
villagesHeaderMessage: ["Villages are open spaces divided up by topic that host hands-on activities, ",
"demos, and workshops throughout the conference. They are generally less formal than the standard ",
"tracks and offer an alternative learning environment from the straight talk/lecture structure. ",
"They're also a great place to socialize and make contacts in the community!"]
villagesHeaderMessageFloor: # Visit the CTF space in the...

#-----------------------------------------------
# Event Intro
#-----------------------------------------------
eventImage: "nyc_skyline.webp"
eventTitle: "BSidesNYC"
eventDate: "17 October 2026"
eventInfo: "The next BSidesNYC will take place in 17 October 2026. To stay updated on volunteer opportunities, and other news, follow us on Twitter <a href=\"https://twitter.com/bsidesnyc\" target=\"_blank\">@BSidesNYC</a> and sign up for the mailing list."
eventButtons:
 - {permalink: "/sponsors/", text: "Become a sponsor", id: "sponsors"}

#-----------------------------------------------
# Location Block
#-----------------------------------------------
locationBlockTitle: "Location"
eventLocationName: "Digital Forensics and Cybersecurity Program @ John Jay College of Criminal Justice"
eventStreetAddress: "524 W 59th St."
eventAddressLocality: "New York"
eventAddressLocalityRegion: "NY"
eventPostalCode: "10019"
eventAddressCountry: "USA"
eventNavigationLink: https://goo.gl/maps/7vwHt4ARqjr
eventStartTime: "2026-10-17T08:00"
eventDoorTime: "09:00"
eventEndTime: "2026-10-17T17:00"
eventPlaceCoordinates: "4087709863, -73.9899653"
mapCenterCoordinates: "40.7709863, -73.9899653"
mapMobileCenterCoordinates: "40.7709863, -73.9899653"

#-----------------------------------------------
# Venue Getting Here Info
#-----------------------------------------------
directionDetailsImage: "columbus_circle.webp"
directionDetailsTitle: "Getting Here"
directionDetailsCards:
 - {title: "Airports", information: 'The conference is easily accessible from the <b>JFK</b>, <b>LGA</b>, or <b>EWR</b> airports via public transportation (subway, bus, taxi) or ride-sharing services (uber, lyft etc.)'}
 - {title: "Public Transit", information: "The closest subway station is <b>59 St. - Columbus Circle</b> (A,B,C & D lines). From this stop, it is less than a .5 mile walk."}
 - {title: "Hotels", information: "<a href='https://www.marriott.com/en-us/hotels/nycft-fairfield-inn-and-suites-new-york-manhattan-central-park/overview/'>Fairfield Inn & Suites New York Manhattan/Central Park</a> is right next door."}

#-----------------------------------------------
# Sponsors
#-----------------------------------------------
sponsorsUrl: "/sponsors/"
sponsorshipKitUrl: "/assets/BSidesNYC-0x06-Sponsorship-Prospectus.pdf"

#-----------------------------------------------
# Subscribe
#-----------------------------------------------
subscribeTitle: "Subscribe for updates"
subscribeInfo: "^^^ Please ignore this message above from our mailing list provider. We use the free edition, so this get embedded.<p>We'll only use your email for BSidesNYC announcements. We respect privacy, and don't provide anyone (including sponsors) with this type of information."

#-----------------------------------------------
# Registration | Tickets
#-----------------------------------------------
# If registrationOpen is true, the registration_open content will be shown if:
#   - its after registrationOpenDate; or 
#   - registrationOpenDate is null
#
# if registrationOpen is false, only the registration_closed content will be shown
#
registrationOpen: False
registrationOpenDate: "2026-09-25T20:00:00-04:00"
registrationLink: https://www.ticketleap.events/tickets/bsidesnyc/bsidesnyc-0x05

#-----------------------------------------------
# Venue
#-----------------------------------------------
venueTitle: John Jay College of Criminal Justice
venueAddress: 524 W. 59th Street, New York, NY
venueWiFiSSID: John Jay Events
venueWiFiPW: Events@Jay24
venuePhotosPrimary: atrium.webp
venuePhotosSecondary:
  - 240.webp
  - L615.webp
  - L763.webp
venueMapsIntro: "Tracks are split across multiple floors. You'll enter and register on the Ground floor where the Red Track (L.63), Keynote (L.63), and Entrepreneur Track (L.61) are. Go down via stairs or elevator to Lower Level (L2) for the Blue Track (L2.84) and Other Track (L2.85). Go up via elevator to the 6th Floor for the Villages (Moot Court) and to the 9th for CTF."
venueFloorMaps:
  - name: Ground Floor (L)
    divId: map-l
    image: 2025_bsidesnyc_jj_GROUND_L1-1.webp
  - name: Lower Level (L2)
    image: 2025_bsidesnyc_jj_LOWER_LEVEL_L2-1.webp 
    divId: map-l2
  - name: 1st Floor
    image: 2025_bsidesnyc_jj_1ST_FLOOR-1.webp
    divId: map-1
  - name: 2nd Floor
    image: 2025_bsidesnyc_jj_2ND_FLOOR-1.webp
    divId: map-2

#-----------------------------------------------
# Volunteers
#-----------------------------------------------
volunteersTitle: "Want to Volunteer?"
volunteersSubscribeTitle: "Join the Team"

#-----------------------------------------------
# CTF 
#-----------------------------------------------
ctfHeader: Game On! 
ctfHeaderMessage: ["We are so excited to offer multiple Capture The Flag (CTF) competitions. ",
"Play one or play them all! All CTFs require a laptop and have both offensive and defensive challenges."]
ctfHeaderMessageFloor: # Visit the CTF space in the Cafeteria/Student Dining Hall (second floor, room 2.64)

#-----------------------------------------------
# Sessionize Links
#-----------------------------------------------
sessionizeJsonSpeakerList: https://sessionize.com/api/v2/sfqscpbj/view/Speakers
sessionizeJsonSessionList: https://sessionize.com/api/v2/sfqscpbj/view/Sessions
sessionizeJsonAllData: https://sessionize.com/api/v2/sfqscpbj/view/All
# Important: Select "Use UTC timezone for schedule" for the schedule grid in sessionize
sessionizeJsonScheduleGrid: https://sessionize.com/api/v2/sfqscpbj/view/GridSmart

